apiVersion: v1
kind: Service
metadata:
  labels:
    app: frontend-svc
  name: frontend-svc
spec:
  ports:
  - name: http
    port: 5000
    protocol: TCP
    targetPort: http
  selector:
    app: frontend-svc
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: frontend-svc
  name: frontend-svc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-svc
  template:
    metadata:
      labels:
        app: frontend-svc
    spec:
      containers:
      - image: mareimorsy/frontend-svc
        imagePullPolicy: Always
        name: frontend-svc
        ports:
        - containerPort: 5000
          name: http
          protocol: TCP
        resources: {}