version: 2
jobs:
  build:
    branches:
      only:
        - master
    docker:
      - image: mareimorsy/light-base

    working_directory: ~/

    steps:
      - checkout

      # - setup_remote_docker:
      #     docker_layer_caching: true

      - run:
          name: install npm dependancies
          command: |
            pwd
            ls
            cd ~
            ls
            cd alert-svc
            npm install

      # - run:
      #     name: "Log in to Docker Hub"
      #     command: | 