version: 2
jobs:
  build:
    branches:
      only:
        - master
    docker:
      - image: mareimorsy/basic-cicd

    working_directory: ~/cloider-mono-repo

    steps:
      - checkout

      - setup_remote_docker:
      #     docker_layer_caching: true

      - run:
          name: install npm dependancies
          command: |
            cd alert-svc
            ls
            npm install
            docker build -t mareimorsy/alert-svc .

      # - run:
      #     name: "Log in to Docker Hub"
      #     command: | 