apiVersion: v1
kind: Service
metadata:
  labels:
    app: test-svc
  name: test-svc
  namespace: default
spec:
  ports:
  - name: http
    port: 6000
    protocol: TCP
    targetPort: http
  - name: http2
    port: 7000
    protocol: TCP
    targetPort: http2
  selector:
    app: test-svc
  type: ClusterIP
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: test-svc
  name: test-svc
spec:
  containers:
  - image: mareimorsy/test-svc
    ports:
    - containerPort: 6000
      name: http
      protocol: TCP
    - containerPort: 7000
      name: http2
      protocol: TCP
    name: test-svc
  restartPolicy: Never